services:
  - type: web
    name: my-python-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"  # Replace with your actual start command
    envVars:
      - key: PORT
        value: 8000
